### PR TITLE
Fixes for tests and rest

### PR DESCRIPTION
**Pull request by anjo**
So the test now pass as well as in your version. In addition there are a few fixes, notably that angular.config() doesn't have a name, so it needs it's own signature.

Also - since it's a drag to maintain the signatures, it might be a good idea to have then created ad-hoc.

### CODE REVIEW

**Comment by anjo** [comment]
BTW: did you get the message I sent you via mail?

**Comment by anjo** [comment]
Added support for:

https://groups.google.com/forum/?fromgroups=#!topic/angular/kbOe8pr_1ZM

"config" and "value" don't work yet, though.

**Comment by anjo** [comment]
BTW: I don't think your approach with the fixed signatures will work once you consider chaining. Basically, you need to get to the deepest node and check if there is a "angular" in it. If that is the case, then rewind the stack and fix up as needed...

**Comment by btford** [comment]
> BTW: did you get the message I sent you via mail?

Yes; been super busy lately, but I'll get back to you soon.

> BTW: I don't think your approach with the fixed signatures will work once you consider chaining. Basically, you need to get to the deepest node and check if there is a "angular" in it. If that is the case, then rewind the stack and fix up as needed...

I agree. It was not my intention to use that as a long-term solution. You have to do some forward taint analysis type stuff which won't really fit just looking at rote patterns in the AST.

**Comment by btford** [comment]
I just pushed my own implementation, which I think is a bit cleaner.

**Pull request closed without merging**
